Build examples from CMake rather than executable
gazebosim/gz-math pull request #482
Opened 2022-08-10 18:43 UTC by mjcarroll

# 🦟 Bug fix

## Summary

Part of https://github.com/gazebosim/gz-cmake/pull/301

Test by building gz-math as normal and then running the "EXAMPLES_Configure_TEST" and "EXAMPLES_Build_TEST" via ctest.

## Checklist
- [ ] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2022-08-10 19:44 UTC, mjcarroll commented
Tested locally on Windows with:

```
colcon build --packages-up-to gz-math7 --merge-install
Summary: 3 packages finished [5 min 20s]

colcon test --packages-select gz-math7 --merge-install
Summary: 1 package finished [31.9s]
```

I also found a neat side effect, this lets us additionally turn on `ninja` on windows:

```
colcon build --packages-up-to gz-math7 --merge-install
Summary: 3 packages finished [1 min 1 s]

colcon test --packages-select gz-math7 --merge-install
Summary: 1 package finished [22.1s]
```

2023-04-17 20:34 UTC, azeey approved these changes

2023-05-24 16:13 UTC, mjcarroll commented
@osrf-jenkins retest this please

2023-05-26 15:55 UTC, mjcarroll commented
@osrf-jenkins retest this please

2023-07-17 08:30 UTC, ahcorde requested changes
Changes LGTM, but CI is ugly, all python tests are failing

2023-07-17 21:47 UTC, ahcorde approved these changes

2023-07-17 21:55 UTC, merged