Added MecanumDriveOdometry
gazebosim/gz-math pull request #549
Opened 2023-08-23 10:55 UTC by ahcorde

# 🎉 New feature

Closes https://github.com/gazebosim/gz-math/issues/548

## Summary

Added MecanumDriveOdometry

## Checklist
- [x] Signed all commits for DCO
- [x] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [x] Consider updating Python bindings (if the library has them)
- [x] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [x] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [x] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2023-08-23 14:28 UTC, azeey commented
Is it okay if we wait till after Harmonic for this?

2023-08-23 14:35 UTC, ahcorde commented
this is targeting Fortress, but we can wait no problem

2023-08-23 15:49 UTC, azeey commented
> this is targeting Fortress, but we can wait no problem

I understand, but I think we should focus our review efforts on `beta` labeled PRs.

2023-10-05 16:47 UTC, ahcorde commented
friendly ping @azeey @scpeters or @adityapande-1995

2023-10-06 19:19 UTC, azeey requested changes

2023-10-06 19:19 UTC, azeey commented on src/python_pybind11/src/MecanumDriveOdometry.cc
> +                    py::buffer_protocol(),
Do we need `py::buffer_protocol` here? If so, doesn't it require implementing `def_buffer` (https://pybind11.readthedocs.io/en/stable/advanced/pycpp/numpy.html)

2023-10-06 19:19 UTC, azeey commented on src/python_pybind11/src/MecanumDriveOdometry.cc
> +                    py::dynamic_attr())
Why do we need `py::dynamic_attr`?

2023-10-06 19:19 UTC, azeey commented on src/python_pybind11/test/MecanumDriveOdometry_TEST.py
> +        odom.init(datetime.timedelta())
Should this use `startTime`?

2023-10-06 19:19 UTC, azeey commented on src/python_pybind11/test/MecanumDriveOdometry_TEST.py
> +                    time1 - startTime)
The C++ version uses just `time1` here.

2023-10-06 19:19 UTC, azeey commented on src/python_pybind11/test/MecanumDriveOdometry_TEST.py
> +                    time2 - startTime)
This is also different from the C++ test

2023-10-06 19:19 UTC, azeey commented on src/python_pybind11/test/MecanumDriveOdometry_TEST.py
> +        odom.update(Angle(1.0 * math.pi / 180),
Use `math.radians`

2023-10-06 19:21 UTC, azeey requested changes
Looks good overall. Just a few issues with pybind11 options and differences with the C++ test

2023-10-06 19:21 UTC, azeey requested changes
Looks good overall. Just a few issues with pybind11 options and differences with the C++ test

2023-10-16 13:02 UTC, ahcorde commented
@azeey Time is a little bit different in Python, you can take a look the `DiffDriveOdometry_TEST.py` test,

2023-11-14 08:49 UTC, ahcorde commented
friendly ping @azeey

2023-11-27 20:47 UTC, azeey commented
> @azeey Time is a little bit different in Python, you can take a look the `DiffDriveOdometry_TEST.py` test,

So from the [pybind11 docs](https://pybind11.readthedocs.io/en/stable/advanced/cast/chrono.html#provided-conversions), it looks like `std::chrono::steady_clock::time_point` is converted to `datetime.timedelta`. This makes it really inconvenient to use since `datetime.timedelta()` always returns a "0" time delta as opposed to the current monotonic (in C++ `steady_clock`) time. One option is to use `datetime.timedelta(time.monotonic())` to initialize `startTime` instead of `datetime.datetime.now()`.

2023-11-27 20:49 UTC, azeey commented on src/python_pybind11/src/MecanumDriveOdometry.cc
> +                    py::buffer_protocol(),
I don't think this has been addressed

2023-12-07 11:59 UTC, j-rivero commented
@osrf-jenkins run tests

2023-12-14 12:44 UTC, ahcorde commented
@azeey I added your feedback

2023-12-14 15:27 UTC, azeey commented
> @azeey I added your feedback

Thanks. I think now the test can be updated to match the C++ version. Specifically, `odom.init(startTime)` instead of `odom.init(datetime.timedelta())` and remove `startTime` from `odom.update` calls.

2024-02-13 10:19 UTC, ahcorde commented
> Thanks. I think now the test can be updated to match the C++ version. Specifically, `odom.init(startTime)` instead of `odom.init(datetime.timedelta())` and remove `startTime` from `odom.update` calls.

@azeey Included feedback

2024-02-13 15:50 UTC, azeey commented on src/python_pybind11/test/DiffDriveOdometry_TEST.py
>          odom.init(datetime.timedelta())
```suggestion
        startTime = datetime.timedelta(time.monotonic())
        odom.init(startTime)
```

then update
`odom.update(..., ..., time1)`

2024-02-13 15:50 UTC, azeey commented on src/python_pybind11/test/DiffDriveOdometry_TEST.py
>          odom.init(datetime.timedelta())
```suggestion
        startTime = datetime.timedelta(time.monotonic())
        odom.init(startTime)
```


then update
`odom.update(..., ..., time1)`

2024-02-13 15:50 UTC, azeey commented on src/python_pybind11/test/DiffDriveOdometry_TEST.py
We need to make the `odom.init` and `odom.update` changes to `time2` as well.

2024-02-13 21:47 UTC, azeey approved these changes

2024-02-13 22:16 UTC, merged