Added box examples in cpp and python
gazebosim/gz-math pull request #584
Opened 2024-03-23 11:28 UTC by ms-jagadeeshan

# 🎉 New feature

- Part of #300 

## Summary
Added cpp and python example for Box class.

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2024-03-25 14:55 UTC, ahcorde requested changes
please in the cpp code include spaces in all operators and separators `<<`, `=`, `,`, etc

2024-03-25 14:55 UTC, ahcorde commented on examples/box_example.cc
> +//! [Create a box]
this kind of comments `//!` are usefull if you are gogin to write a tutorial too, otherwise you can remove them

2024-03-25 14:55 UTC, ahcorde commented on examples/box_example.cc
> +  auto size=box.Size();
```suggestion
  auto size = box.Size();
```

2024-03-25 14:55 UTC, ahcorde commented on examples/box_example.cc
> +  std::cout<<"\nDefault box size: \nLength: "<<size[0]<<" Width: "<<size[1]<<" Height: "<<size[2]<<std::endl;
```suggestion
  std::cout << "Default box size Length: " << size[0] << " Width: " << size[1] 
            << " Height: " << size[2] << std::endl;
```

2024-03-25 14:55 UTC, ahcorde commented on examples/box_example.cc
> +  box.SetSize(4.0,4.0,3.0);
```suggestion
  box.SetSize(4.0, 4.0, 3.0);
```

2024-03-25 14:55 UTC, ahcorde commented on examples/box_example.py
> +print("\nCenter of volume below:")
```suggestion
print("Center of volume below:")
```

2024-03-25 14:55 UTC, ahcorde commented on examples/box_example.py
> +print("\nVertices Below:")
```suggestion
print("Vertices Below:")
```

2024-03-25 14:55 UTC, ahcorde commented on examples/box_example.py
> +print("\nIntersection points:")
```suggestion
print("Intersection points:")
```

2024-03-25 14:55 UTC, ahcorde commented on examples/box_example.py
> +print("\nInertial matrix:")
```suggestion
print("Inertial matrix:")
```

2024-03-25 19:24 UTC, ms-jagadeeshan commented
@ahcorde I have did the suggested changes.
Do we have cpplint(CPPLINT.CFG) and clang-tidy(.clang-tidy) config file for gazebo codestyle?
I code in neovim with language servers, formaters, linters enabled, which check for config file in 
project root directory, if config file  not found, then formats in default way(this mess the formatting), so i turned of my linters and formatters.
We should have linter and formatters config, may be in a gist or in every repo or somewhere else. So it could be downloaded and sym linked locally in project root, and code could be automatically formatted. What do you say?

2024-08-06 04:33 UTC, arjo129 approved these changes
LGTM. Tested it works fine.

2024-08-07 03:48 UTC, arjo129 commented
@ahcorde can we proceed to merge this.

2024-08-12 19:36 UTC, ahcorde approved these changes

2024-08-12 19:43 UTC, merged