Forward port #603 to main
gazebosim/gz-math pull request #604
Opened 2024-07-02 13:10 UTC by mjcarroll

Forward port #603

2024-07-02 13:11 UTC, ahcorde approved these changes

2024-07-02 19:58 UTC, scpeters commented on include/gz/math/Helpers.hh
> +  constexpr auto GZ_DEPRECATED(7) IGN_NINE_SIZE_T  = &GZ_NINE_SIZE_T;
these should not be forward-ported

2024-07-02 20:15 UTC, scpeters requested changes

2024-07-02 20:15 UTC, scpeters commented on include/gz/math/Stopwatch.hh
>          = std::chrono::steady_clock;
this deprecated using statement should not be in the `Stopwatch` class

2024-07-02 20:15 UTC, scpeters commented on include/gz/math/Stopwatch.hh
> +  using clock = std::chrono::steady_clock;
this is old

2024-07-18 02:50 UTC, scpeters commented
this has conflicts; I've opened https://github.com/gazebosim/gz-math/pull/611 as an alternative

2024-07-18 15:34 UTC, mjcarroll commented
Replaced by #611

2024-07-18 15:34 UTC, closed without merging